service: blog

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  versionFunctions: false
  # stage: dev
  environment:
    ARTICLES_TABLE: ${self:custom.articles.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:ListStreams
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${self:custom.region}:*:table/${self:custom.articles.tableName}"

functions:
  listArticles:
    handler: src/index.listArticles
    events:
      - http: GET articles
  createArticle:
    handler: src/index.createArticle
    events:
      - http: POST articles
  getArticle:
    handler: src/index.getArticle
    events:
      - http: GET articles/{id}
  updateArticle:
    handler: src/index.updateArticle
    events:
      - http: POST articles/{id}
  deleteArticle:
    handler: src/index.deleteArticle
    events:
      - http: DELETE articles/{id}
  articleCompute:
    handler: src/index.articleCompute
    events:
      - stream:
          type: dynamodb
          batchSize: 1
          startingPosition: LATEST
          arn:
            Fn::GetAtt: [ ArticlesTable, StreamArn ]

resources:
  Resources:
    ArticlesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.articles.tableName}
        StreamSpecification:
          StreamViewType: NEW_AND_OLD_IMAGES

custom:
  stage: ${opt:stage, self:provider.stage}
  region: ${opt:region, self:provider.region}
  articles:
    tableName: ${self:custom.stage}-articles

  # serverless-dynamodb-local - Offline DynamoDB
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      dbPath: ${env:PWD}/.dynamodb/
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true

  # Ensure local env attaches to local ddb
  serverless-offline-dynamodb-streams:
    endpoint: http://localhost:8000
    region: ${self:custom.region}
    accessKeyId: root
    secretAccessKey: root
    skipCacheInvalidation: false

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline-dynamodb-streams
  - serverless-offline
