service: blog

provider:
  name: aws
  runtime: nodejs8.10
  region: us-west-2
  versionFunctions: false
  # stage: dev
  environment:
    ARTICLES_TABLE: ${self:custom.articles.tableName}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Resource: "arn:aws:dynamodb:${self:provider.region}:*:*"
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:custom.articles.tableName}"

functions:
  listArticles:
    handler: src/index.listArticles
    events:
      - http: GET articles
  createArticle:
    handler: src/index.createArticle
    events:
      - http: POST articles
  getArticle:
    handler: src/index.getArticle
    events:
      - http: GET articles/{id}
  updateArticle:
    handler: src/index.updateArticle
    events:
      - http: POST articles/{id}

resources:
  Resources:
    ArticlesTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.articles.tableName}

custom:
  stage: ${opt:stage, self:provider.stage}
  articles:
    tableName: ${self:custom.stage}-articles
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
      noStart: true

plugins:
  - serverless-plugin-typescript
  - serverless-dynamodb-local
  - serverless-offline
